name = "SimpleNLUtils"
uuid = "2d4e91ba-f49c-4cf8-8b04-70606b35ede9"
authors = ["Sungho Shin <sungho.shin@wisc.edu>"]
version = "0.1.0"

[deps]
SimpleNL = "7bbef9ca-9061-49de-8b0e-60c2db5b3b29"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"
SimpleNL = "0.1"